# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 793aae4bc0eeab46c9c6715cf7958657f86c540895e852d50e07969ac8894e1153c6ef01d09e77fb2095f0154cb40635f0a8150da1bf20221c17fbd6e163f1bb

test:
  secret_key_base: 388d8bd4e8ff9163b65b019e0b124e4daae9415f7b2a2dbfc106177fdf53a972199ffa4037ad95072e350cf2921ae3799504ca14be0ffd527f11dae4eb2f5dac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
